In [3]:
import numpy as np

In [4]:
array = np.arange(20).reshape(5, 4)
print(array)
print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]



In [5]:
print(np.argmax(array))

19


In [ ]:
##Add more code...